@echo off
setlocal enabledelayedexpansion

:: ============================================================
:: Pointify POS — Auto-start Setup
:: Run ONCE as Administrator.
:: After this, the POS server starts at every Windows boot —
:: no console window and no login required.
::
:: Prerequisites:
::   - Node.js installed (https://nodejs.org, LTS version)
::   - .env file present in this folder (see SETUP.md Step 4)
::   - server\dist\index.cjs present (built on Replit)
:: ============================================================

echo.
echo ============================================================
echo  Pointify POS -- Auto-start Setup
echo ============================================================
echo.

:: Must run as Administrator (Task Scheduler registration requires it)
net session >nul 2>&1
if errorlevel 1 (
    echo ERROR: This script must be run as Administrator.
    echo Right-click setup-autostart.bat and choose "Run as administrator".
    pause
    exit /b 1
)

:: ---- Pre-flight checks ----

where node >nul 2>&1
if errorlevel 1 (
    echo ERROR: Node.js is not installed.
    echo Install from https://nodejs.org ^(LTS^) and restart the PC, then re-run.
    pause
    exit /b 1
)

if not exist "%~dp0.env" (
    echo ERROR: .env file not found in %~dp0
    echo Follow SETUP.md Step 4 to create it, then re-run this script.
    pause
    exit /b 1
)

if not exist "%~dp0server\dist\index.cjs" (
    echo ERROR: server\dist\index.cjs not found.
    echo Build on Replit ^(npm run build^) and copy server\dist\ here, then re-run.
    pause
    exit /b 1
)

:: ---- Resolve absolute path to node.exe ----
for /f "delims=" %%N in ('where node 2^>nul') do (
    set "NODE_EXE=%%N"
    goto :found_node
)
:found_node
echo Node.js: %NODE_EXE%

:: ---- Install server runtime dependencies if missing ----
if not exist "%~dp0server\node_modules\.package-lock.json" (
    echo.
    echo Installing server dependencies ^(first run only^)...
    cd /d "%~dp0server"
    npm install --omit=dev
    if errorlevel 1 (
        echo ERROR: Failed to install server dependencies.
        pause
        exit /b 1
    )
    cd /d "%~dp0"
)

:: ---- Install PM2 globally if not already present ----
where pm2 >nul 2>&1
if errorlevel 1 (
    echo.
    echo Installing PM2 ^(Node.js process manager^)...
    npm install -g pm2
    if errorlevel 1 (
        echo ERROR: Failed to install PM2. Check your internet connection.
        pause
        exit /b 1
    )
    echo PM2 installed.
) else (
    echo PM2 is already installed.
)

:: ---- Resolve the absolute path to the pm2 JS entry point ----
:: We call node directly (not the pm2.cmd shim) so it works under SYSTEM
for /f "delims=" %%G in ('npm root -g 2^>nul') do set "NPM_GLOBAL_MODULES=%%G"
set "PM2_JS=%NPM_GLOBAL_MODULES%\pm2\bin\pm2"
if not exist "%PM2_JS%" (
    echo ERROR: Cannot locate PM2 module at %PM2_JS%
    echo Try reinstalling PM2: npm install -g pm2
    pause
    exit /b 1
)
echo PM2 module : %PM2_JS%

:: ---- Set PM2_HOME inside the install folder ----
:: Using the install folder (not %USERPROFILE%) lets the SYSTEM account
:: read the same saved process list that the setup user wrote.
set "PM2_HOME=%~dp0.pm2"
if not exist "%PM2_HOME%" mkdir "%PM2_HOME%"
echo PM2_HOME   : %PM2_HOME%

:: ---- Start the server under PM2 and save the process list ----
echo.
echo Starting Pointify POS under PM2...
cd /d "%~dp0"
"%NODE_EXE%" "%PM2_JS%" start ecosystem.config.js
if errorlevel 1 (
    echo ERROR: PM2 failed to start the server.
    echo Check that server\dist\index.cjs exists and .env is correct.
    pause
    exit /b 1
)

"%NODE_EXE%" "%PM2_JS%" save
if errorlevel 1 (
    echo WARNING: pm2 save failed. The process list may not survive a reboot.
)
echo PM2 process list saved to %PM2_HOME%\dump.pm2

:: ---- Write the boot-time launcher script ----
:: Task Scheduler runs this file as SYSTEM at startup.
:: Hard-coded absolute paths so it works with no login environment.
set "LAUNCHER=%~dp0pm2-autostart.bat"
(
    echo @echo off
    echo :: Auto-generated by setup-autostart.bat -- do not edit manually
    echo :: Called by Windows Task Scheduler at system startup ^(SYSTEM account^)
    echo set "PM2_HOME=%PM2_HOME%"
    echo cd /d "%~dp0"
    echo "%NODE_EXE%" "%PM2_JS%" resurrect
) > "%LAUNCHER%"
echo Launcher written to %LAUNCHER%

:: ---- Register the Windows Task Scheduler boot task ----
:: /SC ONSTART  — fires at system startup (before any user logs in)
:: /RU SYSTEM   — runs as LocalSystem (no password needed, full local access)
:: /delay 0:30  — 30-second delay so network adapters are ready
:: /rl HIGHEST  — highest privilege level
echo.
echo Registering Windows Task Scheduler task...
schtasks /delete /tn "PointifyPOS" /f >nul 2>&1
schtasks /create /tn "PointifyPOS" /sc ONSTART /delay 0000:30 /ru SYSTEM /tr "\"C:\Windows\System32\cmd.exe\" /c \"%LAUNCHER%\"" /rl HIGHEST /f
if errorlevel 1 (
    echo ERROR: Failed to register the startup task.
    echo Make sure you are running as Administrator and try again.
    pause
    exit /b 1
)

echo Task registered. Verify in Task Scheduler ^(taskschd.msc^) under Task Scheduler Library.

echo.
echo ============================================================
echo  SUCCESS -- Pointify POS will now start at every Windows boot.
echo             No login is required.
echo.
echo  Day-to-day commands ^(run in any Command Prompt^):
echo.
echo    pm2 list                    -- show whether the server is running
echo    pm2 logs pointify-pos       -- view live server logs
echo    pm2 restart pointify-pos    -- restart ^(e.g. after updating files^)
echo    pm2 stop pointify-pos       -- stop the server
echo    pm2 start ecosystem.config.js -- start after a manual stop
echo.
echo  To remove auto-start:
echo    schtasks /delete /tn "PointifyPOS" /f
echo ============================================================
echo.
pause
