// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/attendant-dashboard/Current.tsx": () => import("../components/mockups/attendant-dashboard/Current.tsx"),
  "./components/mockups/attendant-dashboard/SidebarNav.tsx": () => import("../components/mockups/attendant-dashboard/SidebarNav.tsx"),
  "./components/mockups/attendant-dashboard/TileGrid.tsx": () => import("../components/mockups/attendant-dashboard/TileGrid.tsx")
};
